[cases.estavayer_centre_ville]
pandapower_file=".cache/input/estavayer/feeders/feeder_centre_ville.p"
load_allocation_folder=".cache/input/estavayer/load_allocation/centre_ville"
geojson_file=".cache/input/estavayer/estavayer.geojson"
