[cases.estavayer_centre_ville]
pandapower_file=".cache/input/estavayer/feeders/feeder_centre_ville.p"
load_allocation_folder=".cache/input/estavayer/load_allocation/centre_ville"
load_gpkg_file=".cache/input/estavayer/estavayer_loads.gpkg"
load_duckdb_file=".cache/input/estavayer/estavayer_loads.db"
geojson_file=".cache/input/estavayer/estavayer.geojson"

