[cases.estavayer_centre_ville]
pandapower_file=".cache/input/estavayer/feeders/feeder_centre_ville.p"
load_allocation_folder=".cache/input/estavayer/load_allocation/centre_ville"

[cases.estavayer]
geojson_file=".cache/input/estavayer/estavayer.geojson"


[outputs.estavayer]
gpkg_file=".cache/input/estavayer/estavayer_loads.gpkg"
duckdb_file=".cache/input/estavayer/estavayer_loads.db"