EACH_TASK_MEMORY = 1e8  # in bytes

[cache]
figures=".cache/figs"
outputs_admm=".cache/outputs_admm"
outputs_bender=".cache/outputs_bender"
outputs_combined=".cache/outputs_combined"
outputs_expansion=".cache/outputs_expansion"
