apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Use localhost because of network_mode: host
    url: http://localhost:9090 
    isDefault: false
    editable: true

  - name: PostgreSQL
    type: postgres
    uid: "afdfds4gcs45ca"
    access: proxy
    # Use localhost because of network_mode: host
    url: localhost:5432 
    user: postgres
    database: experiments
    isDefault: true # This makes Postgres your primary source
    editable: true
    jsonData:
      database: "experiments"
      sslmode: "disable"
      postgresVersion: 15
      timescaledb: false
    secureJsonData:
      password: "postgres"