apiVersion: 1
datasources:
- access: proxy
  isDefault: true
  jsonData: {}
  name: Prometheus
  secureJsonData: {}
  type: prometheus
  apiVersion: 1
- name: PostgreSQL
  type: postgres
  uid: "afdfds4gcs45ca"
  access: proxy
  url: localhost:5432
  user: postgres
  database: experiments
  editable: true
  postgresVersion: 15
  jsonData:
    sslmode: "disable"
    timescaledb: false
  secureJsonData:
    password: "postgres"