# syntax=docker/dockerfile:1.4
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    network_mode: host
    ports:
      - "${SERVER_MONGODB_PORT}:${SERVER_MONGODB_PORT}"
    volumes:
      - ./data/mongo:/data/mongo
    command: --port ${SERVER_MONGODB_PORT}
    restart: unless-stopped

  grafana:
    build:
      context: grafana
      dockerfile: Dockerfile
    container_name: ray-grafana
    network_mode: host
    environment:
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
    restart: unless-stopped

  python-api:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile
      ssh:
        - default
    container_name: dap-py-api
    network_mode: host
    environment:
      - SERVER_RAY_ADDRESS=${HEAD_HOST}:${SERVER_RAY_PORT}
    ports:
      - "${SERVER_PY_PORT}:${SERVER_PY_PORT}"
    volumes:
      - ${GRB_LICENSE_FILE}:/root/gurobi_license/gurobi.lic:ro
      - ./spill:/tmp/spill
      - ./ray:/tmp/ray
      - ./.cache:/app/.cache:rw
      - ./examples:/app/examples:rw
    stdin_open: true
    tty: true
    restart: unless-stopped

  julia-api:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.julia
    container_name: dap-jl-api
    network_mode: host
    environment:
      - SERVER_JL_PORT=${SERVER_JL_PORT}
      - LOCAL_HOST=${LOCAL_HOST}
    ports:
      - "${SERVER_JL_PORT}:${SERVER_JL_PORT}"
    volumes:
      - ./src/model_expansion:/app/src/model_expansion
      - ./examples:/app/examples
      - ./.cache:/app/.cache:rw
    command: julia --project=/app/src/model_expansion/. /app/src/model_expansion/src/Server.jl ${SERVER_JL_PORT}
    restart: unless-stopped

  ray-head:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.ray
      ssh:
        - default
    container_name: ray-head
    network_mode: host
    environment:
      - SERVER_RAY_PORT=${SERVER_RAY_PORT}
      - SERVER_RAY_DASHBOARD_PORT=${SERVER_RAY_DASHBOARD_PORT}
      - SERVER_RAY_METRICS_EXPORT_PORT=${SERVER_RAY_METRICS_EXPORT_PORT}
      - ALLOC_CPUS=${ALLOC_CPUS}
      - ALLOC_GPUS=${ALLOC_GPUS}
      - ALLOC_RAMS=${ALLOC_RAMS}
      - GRAFANA_PORT=${GRAFANA_PORT}
      - LOCAL_HOST=${LOCAL_HOST}
      - RAY_GRAFANA_HOST=http://${LOCAL_HOST}:${GRAFANA_PORT}
      - RAY_GRAFANA_IFRAME_HOST=http://${LOCAL_HOST}:${GRAFANA_PORT}
      - RAY_GRAFANA_ORG_ID=1
      - RAY_PROMETHEUS_HOST=http://${LOCAL_HOST}:9090
      - RAY_PROMETHEUS_NAME=Prometheus
    ports:
      - "${SERVER_RAY_PORT}:${SERVER_RAY_PORT}"
      - "${SERVER_RAY_DASHBOARD_PORT}:${SERVER_RAY_DASHBOARD_PORT}"
      - "${SERVER_RAY_METRICS_EXPORT_PORT}:${SERVER_RAY_METRICS_EXPORT_PORT}"
      - "9090:9090" # Prometheus
    volumes:
      - ${GRB_LICENSE_FILE}:/root/gurobi_license/gurobi.lic:ro
      - ./ray:/tmp/ray
      - ./spill:/tmp/spill
      - ./.cache:/app/.cache:rw
      - ./examples:/app/examples:rw
    command: /app/start-ray-head.sh
    restart: unless-stopped
    depends_on:
      - grafana
