# syntax=docker/dockerfile:1.4
services:
  renderer:
    image: grafana/grafana-image-renderer:latest
    network_mode: host

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: ray-grafana
    network_mode: host
    environment:
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
      - GF_RENDERING_SERVER_URL=http://localhost:8081/render
      - GF_RENDERING_CALLBACK_URL=http://localhost:${GRAFANA_PORT}
      - GF_USERS_DEFAULT_THEME=light # Options: dark, light, or system
    restart: unless-stopped

  python-api:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.python
    container_name: dap-py-api
    network_mode: host
    environment:
      - SERVER_RAY_ADDRESS=${LOCAL_HOST}:${SERVER_RAY_PORT}
    ports:
      - "${SERVER_PY_PORT}:${SERVER_PY_PORT}"
    volumes:
      - ${GRB_LICENSE_FILE}:/root/gurobi_license/gurobi.lic:rw
      - ../spill:/tmp/spill
      - ../ray:/tmp/ray
      - ../.cache:/app/.cache:rw
      - ../examples:/app/examples:rw
    stdin_open: true
    tty: true
    restart: unless-stopped

  julia-api:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.julia
    container_name: dap-jl-api
    network_mode: host
    environment:
      - SERVER_JL_PORT=${SERVER_JL_PORT}
      - LOCAL_HOST=${LOCAL_HOST}
    ports:
      - "${SERVER_JL_PORT}:${SERVER_JL_PORT}"
    volumes:
      - ../src/model_expansion:/app/src/model_expansion
      - ../examples:/app/examples
      - ../.cache:/app/.cache:rw
    command: julia --project=/app/src/model_expansion/. /app/src/model_expansion/src/Server.jl ${SERVER_JL_PORT}
    restart: unless-stopped

  ray-head:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.ray
    container_name: ray-head
    network_mode: host
    environment:
      - SERVER_RAY_PORT=${SERVER_RAY_PORT}
      - SERVER_RAY_DASHBOARD_PORT=${SERVER_RAY_DASHBOARD_PORT}
      - SERVER_RAY_METRICS_EXPORT_PORT=${SERVER_RAY_METRICS_EXPORT_PORT}
      - ALLOC_CPUS=${ALLOC_CPUS}
      - ALLOC_GPUS=${ALLOC_GPUS}
      - ALLOC_RAMS=${ALLOC_RAMS}
      - GRAFANA_PORT=${GRAFANA_PORT}
      - LOCAL_HOST=${LOCAL_HOST}
      - RAY_GRAFANA_HOST=http://${LOCAL_HOST}:${GRAFANA_PORT}
      - RAY_GRAFANA_IFRAME_HOST=http://${LOCAL_HOST}:${GRAFANA_PORT}
      - RAY_GRAFANA_ORG_ID=1
      - RAY_PROMETHEUS_HOST=http://${LOCAL_HOST}:9090
      - RAY_PROMETHEUS_NAME=Prometheus
    ports:
      - "${SERVER_RAY_PORT}:${SERVER_RAY_PORT}"
      - "${SERVER_RAY_DASHBOARD_PORT}:${SERVER_RAY_DASHBOARD_PORT}"
      - "${SERVER_RAY_METRICS_EXPORT_PORT}:${SERVER_RAY_METRICS_EXPORT_PORT}"
      - "9090:9090" # Prometheus
    volumes:
      - ${GRB_LICENSE_FILE}:/root/gurobi_license/gurobi.lic:rw
      - ../ray:/tmp/ray
      - ../spill:/tmp/spill
      - ../.cache:/app/.cache:rw
      - ../examples:/app/examples:rw
    command: /app/start-ray-head.sh
    restart: unless-stopped
    depends_on:
      - grafana

  db:
    image: postgres:15
    container_name: sim_db
    network_mode: host
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${SERVER_PG_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
