name: Build-sphinx-docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: $(pwd)/src

    steps:
      - uses: actions/checkout@v2

      # Load BOTH private SSH keys in one agent
      - name: Set up SSH for private repos
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_UTILIY_FUNCTIONS }}
            ${{ secrets.SSH_PRIVATE_KEY_DATASCHEMA }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version

      - name: Install dependencies with Poetry
        run: |
          poetry install

      - name: Build HTML
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export PYTHONPATH=$(pwd)/src
          poetry run sphinx-build -b html docs/ docs/_build/html

      - name: Publish docs with ghp-import
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export PYTHONPATH=$(pwd)/src
          poetry run ghp-import -n -p -f docs/_build/html

      - name: Final script
        run: |
          echo Build complete.
